# Generated by Django 2.2.4 on 2019-09-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Telefeno', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Domicilio', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
