# Generated by Django 2.2.4 on 2019-09-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
    ]
