# Generated by Django 2.2.5 on 2019-09-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0002_auto_20190913_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_mascotas', models.IntegerField()),
                ('Razones', models.TextField()),
            ],
        ),
    ]
