# Generated by Django 2.2.5 on 2019-09-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0004_solicitud_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
