# Generated by Django 2.2.5 on 2019-09-16 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0006_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='Telefeno',
        ),
        migrations.AddField(
            model_name='persona',
            name='Telefono',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='Persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Adopcion.Persona', verbose_name='Persona'),
        ),
    ]
