# Generated by Django 2.2.5 on 2019-10-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0002_auto_20190915_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1),
        ),
    ]
